CREATE TABLE gyms (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(300) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    photo VARCHAR(300) NOT NULL
);
